codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "30...100"

  ignore:
    - "rekotlin-router/src/test"

  status:
    project:
      default:
        enabled: yes
        target: auto

    patch:
      default:
        enabled: yes
        target: auto

comment:
  layout: "header, diff, tree"
  behavior: default